apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki-test
commonLabels:
  app: loki-test
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: loki-test
    newName: loki-test
    newTag: latest