apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flask-example
commonLabels:
  app: flask-example
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: flask-example
    newName: flask-example
    newTag: latest
