---
apiVersion: v1
kind: Service
metadata:
  name: flask-example
  labels:
    app: flask-example
spec:
  ports:
    - port: 5000
      name: http
    - port: 8000
      name: http-metrics
  selector:
    app: flask-example
