apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-servicemonitor
  # Change this to the namespace the Prometheus instance is running in
  # annotations:
  #   meta.helm.sh/release-name: my-kube-prometheus-stack
  #   meta.helm.sh/release-namespace: default
  labels:
    app: nginx
    release: my-kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
  selector:
    matchLabels:
      app: nginx
