{
 "title": "Kubernetes DMG v2",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Container CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{namespace!=\"kube-system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace!=\"kube-system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}